### ISSUE TITLE
Installation problems - R version compatibility? 

### ISSUE THREAD

**Issue by ANigsch** [nandadorea/vetsyn#14]
I use R version 4.0.2 (2020-06-22) -- "Taking Off Again"
When I tried to install vetsyn, I received following failure message
---------------------------------------------------------------------------
> install_github("vetsyn",username="nandadorea")
Error in parse_repo_spec(repo) : Invalid git repo specification: 'vetsyn'
Warning message:
1 components of `...` were not used.

We detected these problematic arguments:
* `username`

Did you misspecify an argument? 
----------------------------------------------------------------------------
I cannot find vetsyn via the CRAN repository either. 

Trying to install vetsyn with rtools, I received following failure message.  Any recommendations what I can do? Thx! 
---------------------------------------------------------------
"C:\\PROGRA~1\\R\\rtools40\\usr\\bin\\make.exe" 
> install.packages("vetsyn", type = "source")
Installing package into ‘C:/Users/annet/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘vetsyn’ is not available (for R version 4.0.2)

**Comment by nandadorea** [comment]
Hi, in the wiki you can find the code to install vetsyn, since an update sometime ago on devtools, nowadays the actual command to install is:

install_github("nandadorea/vetsyn")

once it is installed, you can call it normally by
library(vetsyn)

vetsyn is not on CRAN, indeed.

don't hesitate to write again if you experience other problems, I have been finding a few bugs in some functions.
